### ISSUE TITLE
Error when using microfab with TLS

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledgendary/full-stack-asset-transfer-guide#108]
While tinkering with the smart contract dev exercise, which is great by the way, I've tried to enable TLS in the network by adding the following to `MICROFAB_CONFIG` in the `justfile`

```yaml
"tls": {
  "enabled": true
}
```

When running `just microfab` I get now the following error:
```bash
Stating microfab....
7999357e2c05fd60c1e6c6aa8c446421fc12aca4be9e335a58e7a42d4ce446de
weft microfab

Process the ibp-microfab output; generates MSPCreds, Connection Profiles and Application wallets

Options:
      --help       Show help  [boolean]
  -v, --version    Show version number  [boolean]
  -w, --wallet     Path to parent directory of application wallets  [required]
  -p, --profile    Path to the parent directory of Gateway files  [required]
  -m, --mspconfig  Path to the root directory of the MSP config  [required]
  -c, --config     File with JSON configuration from Microfab  - for stdin  [default: "-"]
  -f, --force      Force cleaning of directories  [boolean] [default: false]

SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at MicrofabProcessor.<anonymous> (/usr/local/lib/node_modules/@hyperledger-labs/weft/src/microfab.ts:37:29)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@hyperledger-labs/weft/lib/microfab.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@hyperledger-labs/weft/lib/microfab.js:27:12)
    at MicrofabProcessor.processFile (/usr/local/lib/node_modules/@hyperledger-labs/weft/lib/microfab.js:47:16)
    at /usr/local/lib/node_modules/@hyperledger-labs/weft/src/cli.ts:491:37
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@hyperledger-labs/weft/lib/cli.js:32:71
error: Recipe `microfab` failed with exit code 1
```

Seems that the error is related to weft. Is there something that I was missing to change in order to make it working?
I believe that TLS is not necessary for that exercise :)

**Comment by jt-nti** [comment]
I think there were issues with TLS support in microfab which have hopefully been resolved by IBM-Blockchain/microfab#125
Closing this issue now that this project has migrated to an official sample https://github.com/hyperledger/fabric-samples/tree/main/full-stack-asset-transfer-guide
