### ISSUE TITLE
Client app is refusing to connect with the peer cert 

### ISSUE THREAD

**Issue by jkneubuh** [hyperledgendary/full-stack-asset-transfer-guide#93]
On the microfab env, the application scenario is working fine.  

When connecting to the cloud fabric, the TLS root cert is somehow incorrect, or not passed in correctly, or ... something is wrong with the connect.js, causing the node app to crash with an error.   There is some back and forth between the two scenarios - both are stepping on each other.  Fix this so that they both work with the same ENV / setup and node client.

Error is: 
```
# Build the client application
pushd applications/trader-typescript
~/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript ~/github.com/jkneubuh/full-stack-asset-transfer-guide

npm install

> trader@1.0.0 prepare
> npm run build


> trader@1.0.0 build
> tsc


up to date, audited 176 packages in 3s

34 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm start getAllAssets

> trader@1.0.0 start
> node ./dist/app "getAllAssets"


Unexpected application error: GatewayError: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
    at newGatewayError (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@hyperledger/fabric-gateway/dist/gatewayerror.js:39:12)
    at Object.callback (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@hyperledger/fabric-gateway/dist/client.js:101:67)
    at Object.onReceiveStatus (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/client.js:190:36)
    at Object.onReceiveStatus (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    ... 2 lines matching cause stack trace ...
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: [],
  cause: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
      at Object.callErrorFromStatus (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
      at Object.onReceiveStatus (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
      at Object.onReceiveStatus (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
      at Object.onReceiveStatus (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
      at /Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
  for call at
      at Client.makeUnaryRequest (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
      at /Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@hyperledger/fabric-gateway/dist/client.js:44:110
      at new Promise (<anonymous>)
      at GatewayClientImpl.evaluate (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@hyperledger/fabric-gateway/dist/client.js:44:16)
      at ProposalImpl.evaluate (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/node_modules/@hyperledger/fabric-gateway/dist/proposal.js:50:96)
      at async AssetTransfer.getAllAssets (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/dist/contract.js:41:24)
      at async main (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/dist/commands/getAllAssets.js:14:20)
      at async runCommand (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/dist/app.js:26:13)
      at async main (/Users/jkneubuh/github.com/jkneubuh/full-stack-asset-transfer-guide/applications/trader-typescript/dist/app.js:19:5) {
    code: 13,
    details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  }
}

```

**Comment by jkneubuh** [comment]
The error is somewhere around here: 

https://github.com/hyperledgendary/full-stack-asset-transfer-guide/blob/main/applications/trader-typescript/src/connect.ts#L15-L21

**Comment by jkneubuh** [comment]
The old code was resolving absolute path inputs as `undefined`.  It was working OK for relative paths.

**Comment by jkneubuh** [comment]
Just an honest to goodness bug

Now flattened. 

@mbwhite and @bestbeforetoday can you guys give this a double-check when you are back at the office.
